version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  orchestrator:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/app
    depends_on:
      - qdrant
      - mongo
      - redis
